// GENERATED by canon/scripts/export-folio-feed.ts — do not edit by hand.
// A distilled read of the Canon catalog (4064 works), for the
// "currently into" card. Regenerate: bun run scripts/export-folio-feed.ts

export interface CanonNowItem {
  id: string;
  verb: string;
  title: string;
  creator?: string;
  year?: number;
  note?: string;
  href?: string;
  art?: { src: string; w: number; h: number };
}

export interface CanonLove {
  title: string;
  creator?: string;
  rating: number;
}

export interface CanonFeed {
  generatedAt: string;
  sourceSyncedAt: string;
  totalWorks: number;
  regionCount: number;
  regions: string[];
  now: CanonNowItem[];
  loves: CanonLove[];
}

export const canonFeed: CanonFeed = {
  "generatedAt": "2026-07-28",
  "sourceSyncedAt": "2026-07-28T02:22:51.929Z",
  "totalWorks": 4064,
  "regionCount": 20,
  "regions": [
    "Hip-Hop & Alternative Vibes",
    "Eclectic Rock & Pop",
    "Philosophical Non-Fiction",
    "Indie Action Adventures"
  ],
  "now": [
    {
      "id": "jellyfin:dc21eeedb34456de3863ed56f6e8b3ed",
      "verb": "watching",
      "title": "The Paleface",
      "creator": "Buster Keaton",
      "note": "I’m watching this now — 34% through.",
      "href": "https://www.themoviedb.org/movie/25770",
      "art": {
        "src": "/canon/watched.jpg",
        "w": 240,
        "h": 360
      }
    },
    {
      "id": "steam:730",
      "verb": "playing",
      "title": "Counter-Strike 2",
      "creator": "Valve",
      "note": "This is the game I’m playing now.",
      "href": "https://store.steampowered.com/app/730/",
      "art": {
        "src": "/canon/playing.jpg",
        "w": 240,
        "h": 360
      }
    },
    {
      "id": "abs:512fbb76-e24e-4d01-998e-65f315df39f0",
      "verb": "reading",
      "title": "Distributed Systems: Concepts and Design - Course Listening Edition - Slightly Abridged",
      "creator": "George Coulouris, Jean Dollimore, Tim Kindberg, Gordon Blair",
      "note": "I’m reading this now — 0% through.",
      "href": "https://openlibrary.org/search?q=Distributed%20Systems%3A%20Concepts%20and%20Design%20-%20Course%20Listening%20Edition%20-%20Slightly%20Abridged%20George%20Coulouris%2C%20Jean%20Dollimore%2C%20Tim%20Kindberg%2C%20Gordon%20Blair%202012",
      "art": {
        "src": "/canon/reading.jpg",
        "w": 360,
        "h": 360
      }
    },
    {
      "id": "applemusic:ade-la--prima",
      "verb": "in rotation",
      "title": "PRIMA",
      "creator": "ADÉLA",
      "note": "This is what I’m listening to right now.",
      "href": "https://music.apple.com/nz/search?term=PRIMA%20AD%C3%89LA%202026",
      "art": {
        "src": "/canon/rotation.jpg",
        "w": 360,
        "h": 360
      }
    }
  ],
  "loves": [
    {
      "title": "Wiener-Dog",
      "creator": "Todd Solondz",
      "rating": 10
    },
    {
      "title": "Palindromes",
      "creator": "Todd Solondz",
      "rating": 8
    },
    {
      "title": "Once",
      "creator": "John Carney",
      "rating": 10
    }
  ]
};
