// GENERATED by canon/scripts/export-folio-feed.ts — do not edit by hand.
// A distilled read of the Canon catalog (4130 works), for the
// "currently into" card. Regenerate: bun run scripts/export-folio-feed.ts

export interface CanonNowItem {
  verb: string;
  title: string;
  creator?: string;
  year?: number;
  art?: { src: string; w: number; h: number };
}

export interface CanonLove {
  title: string;
  creator?: string;
  rating: number;
}

export interface CanonFeed {
  generatedAt: string;
  totalWorks: number;
  regionCount: number;
  regions: string[];
  now: CanonNowItem[];
  loves: CanonLove[];
}

export const canonFeed: CanonFeed = {
  "generatedAt": "2026-08-15",
  "totalWorks": 4130,
  "regionCount": 21,
  "regions": [
    "Eclectic Music Mix",
    "Intellectual Documentaries",
    "Contemporary Indie",
    "Indie Adventure"
  ],
  "now": [
    {
      "verb": "watching",
      "title": "IF",
      "creator": "John Krasinski",
      "art": {
        "src": "/canon/watched.jpg",
        "w": 240,
        "h": 360
      }
    },
    {
      "verb": "playing",
      "title": "Big Walk",
      "creator": "House House",
      "art": {
        "src": "/canon/playing.jpg",
        "w": 240,
        "h": 360
      }
    },
    {
      "verb": "reading",
      "title": "Distributed Systems: Concepts and Design - Course Listening Edition - Slightly Abridged",
      "creator": "George Coulouris, Jean Dollimore, Tim Kindberg, Gordon Blair",
      "art": {
        "src": "/canon/reading.jpg",
        "w": 360,
        "h": 360
      }
    },
    {
      "verb": "in rotation",
      "title": "Denya",
      "creator": "Nolan Saburo",
      "art": {
        "src": "/canon/rotation.jpg",
        "w": 360,
        "h": 360
      }
    }
  ],
  "loves": [
    {
      "title": "Maddie's Secret",
      "creator": "John Early",
      "rating": 10
    },
    {
      "title": "Dick",
      "creator": "Andrew Fleming",
      "rating": 10
    },
    {
      "title": "The Odyssey",
      "creator": "Christopher Nolan",
      "rating": 10
    }
  ]
};
