// GENERATED by canon/scripts/export-folio-feed.ts — do not edit by hand.
// A distilled read of the Canon catalog (4252 works), for the
// "currently into" card. Regenerate: bun run scripts/export-folio-feed.ts

export interface CanonNowItem {
  id: string;
  verb: string;
  title: string;
  creator?: string;
  year?: number;
  note?: string;
  href?: string;
  art?: { src: string; w: number; h: number };
}

export interface CanonLove {
  title: string;
  creator?: string;
  rating: number;
}

export interface CanonFeed {
  generatedAt: string;
  sourceSyncedAt: string;
  totalWorks: number;
  regionCount: number;
  regions: string[];
  now: CanonNowItem[];
  loves: CanonLove[];
}

export const canonFeed: CanonFeed = {
  "generatedAt": "2026-08-30",
  "sourceSyncedAt": "2026-08-30T22:25:35.065Z",
  "totalWorks": 4252,
  "regionCount": 22,
  "regions": [
    "Genre-Bending",
    "Eclectic Hip-Hop Fusion",
    "Dark Comedy Fantasies",
    "Golden Age Film Noir"
  ],
  "now": [
    {
      "id": "letterboxd:the-invite-2026",
      "verb": "watching",
      "title": "The Invite",
      "creator": "Olivia Wilde",
      "note": "I’m watching this now — 6% through.",
      "href": "https://www.themoviedb.org/movie/950028",
      "art": {
        "src": "/canon/watched.jpg",
        "w": 240,
        "h": 360
      }
    },
    {
      "id": "steam:2677660",
      "verb": "playing",
      "title": "Indiana Jones and the Great Circle",
      "creator": "MachineGames",
      "note": "This is the game I’m playing now.",
      "href": "https://store.steampowered.com/app/2677660/",
      "art": {
        "src": "/canon/playing.jpg",
        "w": 240,
        "h": 360
      }
    },
    {
      "id": "abs:d2b73170-0356-49ba-acc8-f366ec3f5cfd",
      "verb": "reading",
      "title": "Becoming Steve Jobs: The Evolution of a Reckless Upstart into a Visionary Leader",
      "creator": "Brent Schlender, Rick Tetzeli",
      "note": "I’m reading this now — 36% through.",
      "href": "https://openlibrary.org/search?q=Becoming%20Steve%20Jobs%3A%20The%20Evolution%20of%20a%20Reckless%20Upstart%20into%20a%20Visionary%20Leader%20Brent%20Schlender%2C%20Rick%20Tetzeli%202015",
      "art": {
        "src": "/canon/reading.jpg",
        "w": 360,
        "h": 360
      }
    },
    {
      "id": "applemusic:kuru--backstage-hologram",
      "verb": "in rotation",
      "title": "Backstage hologram",
      "creator": "kuru",
      "note": "This is what I’m listening to right now.",
      "href": "https://music.apple.com/nz/search?term=Backstage%20hologram%20kuru%202026",
      "art": {
        "src": "/canon/rotation.jpg",
        "w": 360,
        "h": 360
      }
    }
  ],
  "loves": [
    {
      "title": "Maddie's Secret",
      "creator": "John Early",
      "rating": 10
    },
    {
      "title": "Dick",
      "creator": "Andrew Fleming",
      "rating": 10
    },
    {
      "title": "The Odyssey",
      "creator": "Christopher Nolan",
      "rating": 10
    }
  ]
};
