import test from "node:test"; import assert from "node:assert/strict";
import { advanceKonami, appendLabHistory, boardState, destinationMode, followLabChoice, KONAMI, LAB_BRANCHES, makeBoard, randomLabMode, reveal, SAFE_RANDOM_MODES, scoreTyping, toggleFlag, restoredSnapshot } from "./lab";
test("Konami unlocks only after exact sequence and restarts safely",()=>{ let i=0, unlocked=false; for(const key of KONAMI) ({index:i,unlocked}=advanceKonami(i,key)); assert.equal(unlocked,true); assert.deepEqual(advanceKonami(4,"x"),{index:0,unlocked:false}); assert.equal(advanceKonami(0,"ArrowUp").index,1); });
test("randomizer can select only non-navigation safe visual modes",()=>{ assert.equal(randomLabMode(0),SAFE_RANDOM_MODES[0]); assert.equal(randomLabMode(.999),SAFE_RANDOM_MODES.at(-1)); for(let i=0;i<100;i++) assert.ok(SAFE_RANDOM_MODES.includes(randomLabMode(i/100))); assert.ok(!SAFE_RANDOM_MODES.includes("gravity" as never)); });
test("minesweeper generation, flags, reveal and win/loss are deterministic",()=>{ const board=makeBoard(3,3,1,()=>0); assert.equal(board.flat().filter(c=>c.mine).length,1); const flagged=toggleFlag(board,0,0); assert.equal(flagged[0][0].flagged,true); assert.equal(reveal(flagged,0,0)[0][0].open,false); const mineIndex=board.flat().findIndex(c=>c.mine), lost=reveal(board,mineIndex%3,Math.floor(mineIndex/3)); assert.equal(boardState(lost),"lost"); let safe=board; for(let y=0;y<3;y++) for(let x=0;x<3;x++) if(!safe[y][x].mine) safe=reveal(safe,x,y); assert.equal(boardState(safe),"won"); });
test("typing scores are local deterministic values",()=>{ assert.deepEqual(scoreTyping("design","desx",60000),{correct:3,accuracy:75,wpm:1}); assert.equal(scoreTyping("x","",0).accuracy,100); });
test("restore clears active mode while preserving page snapshot",()=>{ assert.deepEqual(restoredSnapshot({title:"Portfolio",scrollX:2,scrollY:40,activeMode:"crt"}),{title:"Portfolio",scrollX:2,scrollY:40,activeMode:null}); });
test("every experiment has two deterministic, valid branches",()=>{ for(const [mode,choices] of Object.entries(LAB_BRANCHES)){assert.equal(choices.length,2); for(const [index,choice] of choices.entries()){assert.ok(choice.label);assert.equal(followLabChoice(mode as keyof typeof LAB_BRANCHES,index as 0|1),choice.to); const next=destinationMode(choice.to);assert.ok(next===null||next in LAB_BRANCHES);}} });
test("branch history is bounded and does not duplicate a repeated current step",()=>{ assert.deepEqual(appendLabHistory(["crt"],"crt"),["crt"]); const long=appendLabHistory(["crt","paint","typing","desktop","gravity","ambient","diagnostics","crt"],"paint",4);assert.deepEqual(long,["ambient","diagnostics","crt","paint"]); });
