export type AppId="files"|"about"|"browser"|"terminal"|"notes"|"settings"|"help"|"trash"|"mines"|"snake"|"adventure"|"office";
export type OSWindow={id:string;app:AppId;title:string;x:number;y:number;width:number;height:number;z:number;minimized:boolean;maximized:boolean};
export type OSState={windows:OSWindow[];nextZ:number};
export type OSAction={type:"open";app:AppId;title:string}|{type:"focus";id:string}|{type:"move";id:string;x:number;y:number}|{type:"resize";id:string;width:number;height:number}|{type:"minimize"|"maximize"|"close";id:string};
export const initialOSState:OSState={windows:[],nextZ:2};
export function windowReducer(state:OSState,action:OSAction):OSState{if(action.type==="open"){const old=state.windows.find(w=>w.app===action.app);if(old)return windowReducer(state,{type:"focus",id:old.id});const n=state.windows.length;return{windows:[...state.windows,{id:`${action.app}-${n}`,app:action.app,title:action.title,x:70+n*24,y:55+n*20,width:Math.min(720,innerSafeWidth()),height:Math.min(520,innerSafeHeight()),z:state.nextZ,minimized:false,maximized:false}],nextZ:state.nextZ+1}}if(action.type==="close")return{...state,windows:state.windows.filter(w=>w.id!==action.id)};return{windows:state.windows.map(w=>w.id!==action.id?w:action.type==="focus"?{...w,z:state.nextZ,minimized:false}:action.type==="move"?{...w,x:Math.max(0,action.x),y:Math.max(0,action.y)}:action.type==="resize"?{...w,width:Math.max(300,action.width),height:Math.max(220,action.height)}:action.type==="minimize"?{...w,minimized:true}:action.type==="maximize"?{...w,maximized:!w.maximized,minimized:false}:w),nextZ:action.type==="focus"?state.nextZ+1:state.nextZ}}function innerSafeWidth(){return typeof innerWidth==="number"?innerWidth-32:680}function innerSafeHeight(){return typeof innerHeight==="number"?innerHeight-100:480}
export type FileNode={name:string;kind:"folder"|"file";content?:string;children?:FileNode[]};
export const FILESYSTEM:FileNode={name:"Desktop",kind:"folder",children:[{name:"Projects",kind:"folder",children:[{name:"README.txt",kind:"file",content:"Small products, careful systems, and proof over promises."},{name:"the-door",kind:"folder",children:[{name:"knock-three-times.txt",kind:"file",content:"Try: knock knock knock in Terminal."}]}]},{name:"Documents",kind:"folder",children:[{name:"meeting-that-could-be-a-note.txt",kind:"file",content:"Agenda: cancel the meeting."},{name:"Adventure-pass.txt",kind:"file",content:"The lighthouse keeper trusts people who carry a paper moon."}]},{name:"Games",kind:"folder",children:[{name:"mines.launch",kind:"file",content:"Open Mines from the Start menu."}]},{name:"Recycle Bin",kind:"folder",children:[{name:"final_final_v7_REAL.txt",kind:"file",content:"This was never final."}]}]};
export function traverse(path:string[],root=FILESYSTEM):FileNode|null{let node:FileNode|undefined=root;for(const part of path){node=node.children?.find(x=>x.name===part);if(!node)return null}return node}
const commands=["help","about","ls","date","clear","whoami","fortune","open","knock","vacuum"] as const;
export type TerminalResult={output:string;clear?:boolean;open?:AppId;vacuum?:boolean};
export function parseCommand(raw:string,now="LOCAL TIME"):TerminalResult{const [cmd,...args]=raw.trim().toLowerCase().split(/\s+/);if(!cmd)return{output:""};if(!commands.includes(cmd as never))return{output:`Command not found: ${cmd}. This is a tiny pretend computer, not your shell.`};if(cmd==="help")return{output:"help, about, ls, date, clear, whoami, fortune, open <app>, knock, vacuum"};if(cmd==="about")return{output:"Maxwell OS 1.0. Local, fictional, and mildly overqualified."};if(cmd==="ls")return{output:"Projects  Documents  Games  Recycle Bin"};if(cmd==="date")return{output:now};if(cmd==="clear")return{output:"",clear:true};if(cmd==="whoami")return{output:"guest@portfolio. Excellent disguise."};if(cmd==="fortune")return{output:"A clean interface is often just a well-hidden argument."};if(cmd==="knock")return{output:args.join(" ")==="knock knock"?"A tiny door opens in File Explorer.":"The terminal knocks back."};if(cmd==="vacuum")return{output:"Ant containment protocol requested.",vacuum:true};if(cmd==="open"){const app=args[0] as AppId;return (["files","about","browser","notes","help","mines","snake","adventure","office"] as string[]).includes(app)?{output:`Opening ${app}.`,open:app}:{output:"That app is not on the allowlist."}}return{output:""}}
export type StoryNode={text:string;choices:{label:string;to:string}[];ending?:string};
export const OFFICE_GRAPH:Record<string,StoryNode>={lobby:{text:"At 9:03, the office assigns you one task: choose a door without making it a strategy.",choices:[{label:"Blue door",to:"meeting"},{label:"Stairs",to:"roof"}]},meeting:{text:"The meeting room contains one chair and a slide titled Alignment.",choices:[{label:"Sit",to:"aligned"},{label:"Turn off projector",to:"dark"}]},roof:{text:"The stairs lead to a rooftop vegetable garden maintained by Accounting.",choices:[{label:"Water basil",to:"basil"},{label:"Return to lobby",to:"lobby"}]},aligned:{text:"You align perfectly with the chair. Nobody can find you. Promotion achieved.",choices:[],ending:"The Alignment Ending"},dark:{text:"With the projector off, everyone remembers the meeting was fictional.",choices:[],ending:"The Power Saving Ending"},basil:{text:"The basil approves your quarterly instincts. You resign to become weather.",choices:[],ending:"The Basil Ending"}};
export const ADVENTURE_GRAPH:Record<string,StoryNode>={dock:{text:"Low tide at the town of Elsewhere. A lighthouse blinks in an anxious rhythm.",choices:[{label:"Walk to lighthouse",to:"light"},{label:"Inspect vending oracle",to:"oracle"}]},oracle:{text:"The machine accepts compliments instead of coins and dispenses a paper moon.",choices:[{label:"Compliment its typography",to:"moon"},{label:"Return to dock",to:"dock"}]},moon:{text:"You pocket the paper moon. It smells faintly of toner.",choices:[{label:"Take moon to lighthouse",to:"keeper"}]},light:{text:"The keeper asks for proof that night has been properly filed.",choices:[{label:"Return to oracle",to:"oracle"}]},keeper:{text:"The paper moon completes the beam. Ships now navigate by excellent paperwork.",choices:[],ending:"Harbour Saved, Mostly"}};
export function followStory(graph:Record<string,StoryNode>,node:string,choice:number){const next=graph[node]?.choices[choice]?.to;return next&&graph[next]?next:null}
export type AntState={active:boolean;count:number;generation:number};export function antReducer(s:AntState,a:{type:"release"|"clear";amount?:number}):AntState{return a.type==="clear"?{active:false,count:0,generation:s.generation+1}:{active:true,count:Math.min(80,s.count+(a.amount??18)),generation:s.generation}}
export type SnakePoint={x:number;y:number};export function snakeStep(body:SnakePoint[],dir:SnakePoint,size=12){const h=body[0],next={x:(h.x+dir.x+size)%size,y:(h.y+dir.y+size)%size};return{body:[next,...body.slice(0,-1)],hit:body.some(p=>p.x===next.x&&p.y===next.y)}}
export function safeRestore(s:{title:string;scrollX:number;scrollY:number}){return{...s,active:false,ants:0,timers:0}}
