export type QuizQuestion = { id:string; round:"catalog"|"deep-cut"|"crossover"; prompt:string; options:string[]; answer:number; explanation:string; source:{label:string;href:string} };
const music="https://maxwellyoung.info";
const portfolio="https://dev.maxwellyoung.info/projects";
export const questions:QuizQuestion[]=[
{id:"turn-collab",round:"catalog",prompt:"Who shares the artist credit on Turn It Up?",options:["Eddie Johnston","Thom Haha","Josh Naley","Tom Shackleton"],answer:1,explanation:"Turn It Up is billed to Maxwell Young & Thom Haha, who also share its production credit.",source:{label:"Turn It Up catalog entry",href:music}},
{id:"turn-video",round:"deep-cut",prompt:"Who directed the Turn It Up video?",options:["Nayan Patel","Elijah Broughton","Tom Shackleton","Max Pirrit"],answer:2,explanation:"Tom Shackleton directed the video, shot on MiniDV.",source:{label:"Turn It Up credits",href:music}},
{id:"turn-format",round:"deep-cut",prompt:"What format was the Turn It Up video shot on?",options:["Super 8","MiniDV","16mm","VHS-C"],answer:1,explanation:"Its catalog credit specifies MiniDV, a distinctly turn-of-the-century texture.",source:{label:"Turn It Up credits",href:music}},
{id:"wintour-producer",round:"catalog",prompt:"Who co-produced Wintour with Maxwell?",options:["Eddie Johnston","Ike Zwanikken","Solomon Gutteridge","Thom Haha"],answer:0,explanation:"Wintour was produced by Maxwell Young and Eddie Johnston.",source:{label:"Wintour microsite",href:"https://wintour.maxwellyoung.info/"}},
{id:"wintour-art",round:"deep-cut",prompt:"Who made the artwork for Wintour?",options:["Maxwell Young","Nayan Patel","Elijah Broughton","Millie Dow"],answer:2,explanation:"The release credits Elijah Broughton for its artwork.",source:{label:"Wintour microsite",href:"https://wintour.maxwellyoung.info/"}},
{id:"wintour-place",round:"deep-cut",prompt:"Where was Wintour recorded?",options:["Auckland, New Zealand","London, England","Wellington, New Zealand","Los Angeles, USA"],answer:0,explanation:"The public Wintour page records Auckland, New Zealand as the recording location.",source:{label:"Wintour microsite",href:"https://wintour.maxwellyoung.info/"}},
{id:"flying-time",round:"catalog",prompt:"How long is the 2026 single Flying?",options:["1:52","2:26","3:05","4:04"],answer:0,explanation:"Flying is a compact 1 minute 52 seconds, described as built to loop.",source:{label:"Flying on Apple Music",href:"https://music.apple.com/us/album/flying/1879773855?i=1879773856"}},
{id:"flying-date",round:"catalog",prompt:"On what date did Flying release?",options:["4 April 2026","30 April 2026","4 March 2026","20 July 2026"],answer:0,explanation:"The public release metadata dates Flying to 4 April 2026.",source:{label:"Flying smart link",href:"https://song.link/us/i/1879773856"}},
{id:"freewheelin-art",round:"catalog",prompt:"Who created the artwork for Freewheelin'?",options:["Tom Shackleton","Maxwell Young","Eddie Johnston","Max Pirrit"],answer:1,explanation:"Maxwell made the Freewheelin' artwork, adding visual authorship to the music credit.",source:{label:"Freewheelin' on Apple Music",href:"https://music.apple.com/nz/album/freewheelin-single/1713764743"}},
{id:"fly-art",round:"deep-cut",prompt:"Which pair shares the I Just Wanna Fly artwork credit?",options:["Maxwell Young & Tom Shackleton","Maxwell Young & Nayan Patel","Eddie Johnston & Max Pirrit","Tom Shackleton & Elijah Broughton"],answer:0,explanation:"Tom Shackleton and Maxwell Young share the artwork credit.",source:{label:"I Just Wanna Fly on Apple Music",href:"https://music.apple.com/nz/album/i-just-wanna-fly-single/1713764743"}},
{id:"birthday-count",round:"catalog",prompt:"How many tracks appear on the Birthday Girl EP?",options:["4","5","6","8"],answer:1,explanation:"The EP contains five: My Lovely Liar, Giving Up Again, Floodlight, Did You Have To Grow?, and Believe.",source:{label:"Birthday Girl EP",href:"https://music.apple.com/nz/album/birthday-girl-ep/1640587731"}},
{id:"birthday-josh",round:"deep-cut",prompt:"Which Birthday Girl tracks were co-produced by Josh Naley?",options:["Floodlight & Believe","My Lovely Liar & Believe","Giving Up Again & Floodlight","Did You Have To Grow? & Believe"],answer:0,explanation:"Josh Naley is credited as co-producer on Floodlight and Believe.",source:{label:"Birthday Girl EP",href:"https://music.apple.com/nz/album/birthday-girl-ep/1640587731"}},
{id:"birthday-piano",round:"deep-cut",prompt:"Who played piano on Did You Have To Grow?",options:["Ike Zwanikken","Eddie Johnston","Solomon Gutteridge","Josh Naley"],answer:2,explanation:"Solomon Gutteridge has the track's piano credit.",source:{label:"Birthday Girl EP",href:"https://music.apple.com/nz/album/birthday-girl-ep/1640587731"}},
{id:"birthday-master",round:"deep-cut",prompt:"Who mastered Birthday Girl?",options:["Ike Zwanikken","Josh Naley","Thom Haha","Max Pirrit"],answer:0,explanation:"Ike Zwanikken mastered the five-track EP.",source:{label:"Birthday Girl EP",href:"https://music.apple.com/nz/album/birthday-girl-ep/1640587731"}},
{id:"pair-video",round:"catalog",prompt:"Which two titles were released as a pairing?",options:["Videostar / Cleopatra","Wintour / Flying","Dread! / Hopeless","Believe / No. 5"],answer:0,explanation:"Videostar / Cleopatra is a paired single with artwork by Nayan Patel.",source:{label:"Videostar / Cleopatra",href:"https://music.apple.com/us/album/videostar-cleopatra-single/1550140029"}},
{id:"dread-art",round:"deep-cut",prompt:"Who created the artwork for Dread!?",options:["Nayan Patel","Max Pirrit","Elijah Broughton","Maxwell Young"],answer:1,explanation:"The catalog credits Max Pirrit with the Dread! artwork.",source:{label:"Dread! on Apple Music",href:"https://music.apple.com/nz/album/dread-single/1524674904"}},
{id:"romantics",round:"deep-cut",prompt:"On which release did Maxwell write, produce, record, mix and perform the material?",options:["Only Romantics","Birthday Girl","Wintour","Turn It Up"],answer:0,explanation:"Only Romantics carries the unusually complete self-authored production and performance credit.",source:{label:"Only Romantics EP",href:"https://music.apple.com/us/album/only-romantics-ep/1462528934"}},
{id:"liner",round:"crossover",prompt:"Which design project is a spatial canvas for songs, notes and references?",options:["Silk","Liner","SkillScan","Vape Quit Coach"],answer:1,explanation:"Liner turns music objects, waveforms and references into an infinite-canvas workspace.",source:{label:"Public project catalog",href:portfolio}},
{id:"silk",round:"crossover",prompt:"Which product did Maxwell lead from its first React Native build through launch?",options:["SkillScan","Liner","Silk","Holdspace"],answer:2,explanation:"The public portfolio describes Maxwell leading Silk's mobile app from its first build through launch.",source:{label:"Silk project record",href:portfolio}},
{id:"vqc",round:"crossover",prompt:"Which solo-built iOS product combines coaching, recovery milestones and relapse support?",options:["Liner","Silk","Vape Quit Coach","SkillScan"],answer:2,explanation:"Vape Quit Coach is the portfolio's live behavior-change mobile product.",source:{label:"Vape Quit Coach project record",href:portfolio}},
];
function rng(seed:number){let x=seed>>>0;return()=>{x=(x*1664525+1013904223)>>>0;return x/4294967296}}
export function selectQuestions(seed:number,count=11){const random=rng(seed);const shuffled=[...questions].sort(()=>random()-.5);const cross=shuffled.filter(q=>q.round==="crossover").slice(0,2);const rest=shuffled.filter(q=>q.round!=="crossover").slice(0,count-cross.length);return [...rest,...cross].sort(()=>random()-.5)}
export function scoreAnswers(selected:QuizQuestion[],answers:Record<string,number>){return selected.reduce((n,q)=>n+(answers[q.id]===q.answer?1:0),0)}
export const results=[{min:0,title:"Unverified Lobby Visitor",copy:"You found the archive. Personnel would like a second pass."},{min:4,title:"Catalog Desk Operative",copy:"You know the singles and can navigate a credit sheet without supervision."},{min:7,title:"Cross-Department Liaison",copy:"Music and product records both clear your desk."},{min:9,title:"Senior Personnel Archivist",copy:"You remember names in the small type. The institution is impressed and slightly concerned."},{min:11,title:"Maxwell Professional Doppelgänger",copy:"Near-total clearance. Please report to identity verification."}];
export function resultFor(score:number){return [...results].reverse().find(r=>score>=r.min)!}
