"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { advanceKonami, appendLabHistory, boardState, destinationMode, LAB_BRANCHES, makeBoard, randomLabMode, reveal, scoreTyping, toggleFlag, type Board, type LabDestination, type LabEnding, type LabMode } from "@/lib/lab";
import styles from "./LabShell.module.css";
export const LAB_OPEN_EVENT="portfolio-lab:open", LAB_UNLOCK_EVENT="portfolio-lab:unlock";
const words=["design systems","interaction craft","product engineering","React Native","accessible interfaces","public proof"];
export function LabShell(){
 const [mode,setMode]=useState<LabMode|null>(null), [unlocked,setUnlocked]=useState(false), [flash,setFlash]=useState(false), [history,setHistory]=useState<LabMode[]>([]), [ending,setEnding]=useState<LabEnding|null>(null); const snapshot=useRef<{title:string;x:number;y:number;focus:HTMLElement|null}|null>(null); const cleanup=useRef<(()=>void)[]>([]); const konami=useRef(0);
 const restore=useCallback(()=>{ cleanup.current.splice(0).reverse().forEach(fn=>fn()); document.documentElement.classList.remove(styles.crt); document.body.classList.remove(styles.labBody); const s=snapshot.current; if(s){document.title=s.title; scrollTo(s.x,s.y); requestAnimationFrame(()=>s.focus?.focus());} snapshot.current=null; setMode(null); },[]);
 const open=useCallback((next:LabMode|"random")=>{ restore(); const chosen=next==="random"?randomLabMode(Math.random()):next; snapshot.current={title:document.title,x:scrollX,y:scrollY,focus:document.activeElement as HTMLElement}; setHistory([chosen]);setEnding(null);setMode(chosen); document.body.classList.add(styles.labBody); },[restore]);
 const branch=useCallback((destination:LabDestination)=>{cleanup.current.splice(0).reverse().forEach(fn=>fn());document.documentElement.classList.remove(styles.crt);const next=destinationMode(destination);if(next){setEnding(null);setHistory(old=>appendLabHistory(old,next));setMode(next);}else setEnding(destination.slice(7) as LabEnding);},[]);
 useEffect(()=>{ const saved=sessionStorage.getItem("portfolio-lab-unlocked")==="1"; setUnlocked(saved); const onOpen=(e:Event)=>open((e as CustomEvent<LabMode|"random">).detail); addEventListener(LAB_OPEN_EVENT,onOpen); return()=>removeEventListener(LAB_OPEN_EVENT,onOpen);},[open]);
 useEffect(()=>{ const key=(e:KeyboardEvent)=>{ if(e.key==="Escape"&&mode){e.preventDefault();restore();return;} if(!unlocked&&!/INPUT|TEXTAREA|SELECT/.test((e.target as HTMLElement)?.tagName)){const result=advanceKonami(konami.current,e.key);konami.current=result.index;if(result.unlocked){sessionStorage.setItem("portfolio-lab-unlocked","1");setUnlocked(true);setFlash(true);setTimeout(()=>setFlash(false),1800);dispatchEvent(new Event(LAB_UNLOCK_EVENT));dispatchEvent(new CustomEvent("portfolio-utility:open",{detail:"palette"}));}}}; addEventListener("keydown",key);return()=>removeEventListener("keydown",key);},[mode,restore,unlocked]);
 useEffect(()=>{ if(!mode)return; if(mode==="crt")document.documentElement.classList.add(styles.crt); if(mode==="desktop"||mode==="gravity") activateBlocks(mode,cleanup.current); },[mode]);
 return <>{flash&&<div className={styles.unlock} role="status">LAB ACCESS GRANTED</div>}{unlocked&&<button className={styles.glyph} aria-label="Open Lab commands" onClick={()=>dispatchEvent(new CustomEvent("portfolio-utility:open",{detail:"palette"}))}>⌁</button>}{mode&&<LabTrail history={history} mode={mode} ending={ending} branch={branch} restore={restore}/>} {mode==="minesweeper"&&<Minesweeper close={restore}/>} {mode==="paint"&&<Paint register={fn=>cleanup.current.push(fn)}/>} {mode==="ambient"&&<Ambient register={fn=>cleanup.current.push(fn)}/>} {mode==="typing"&&<Typing/>} {mode==="diagnostics"&&<Diagnostics/>}</>;
}
const endingCopy:Record<LabEnding,string>={"quiet-loop":"You found the quiet loop. It has been waiting without collecting any data.","impossible-window":"The counter opens a window that cannot fit on this desktop. Sensibly, it offers a way out.","green-door":"The green door was only a cursor trail. It still counts as an ending."};
function LabTrail({history,mode,ending,branch,restore}:{history:LabMode[];mode:LabMode;ending:LabEnding|null;branch:(to:LabDestination)=>void;restore:()=>void}){return <aside className={styles.trail} aria-label="Lab path"><nav aria-label="Breadcrumb">Portfolio / Lab / {history.map((item,i)=><span key={`${item}-${i}`}>{i?" / ":""}{item}</span>)}</nav>{ending?<div role="status"><b>Hidden ending</b><p>{endingCopy[ending]}</p><button onClick={()=>branch("diagnostics")}>There is another door</button></div>:<div><small>The corridor branches again.</small>{LAB_BRANCHES[mode].map(choice=><button key={choice.label} onClick={()=>branch(choice.to)}>{choice.label}</button>)}</div>}<button className={styles.escape} onClick={restore}>Return to portfolio <kbd>Esc</kbd></button></aside>}
function activateBlocks(mode:"desktop"|"gravity",cleanups:(()=>void)[]){ const nodes=[...document.querySelectorAll<HTMLElement>("main section, main article")].filter(n=>n.offsetWidth>80).slice(0,6); nodes.forEach((n,i)=>{const old=n.getAttribute("style");const r=n.getBoundingClientRect();n.classList.add(mode==="desktop"?styles.window:styles.falling);n.style.setProperty("--lab-delay",`${i*60}ms`); if(mode==="desktop"){n.style.width=`${r.width}px`;n.style.zIndex=String(7000+i);} let start:{x:number;y:number;left:number;top:number}|null=null; const down=(e:PointerEvent)=>{if((e.target as HTMLElement).closest("a,button,input"))return;start={x:e.clientX,y:e.clientY,left:parseFloat(n.dataset.lx||"0"),top:parseFloat(n.dataset.ly||"0")};n.setPointerCapture(e.pointerId)}; const move=(e:PointerEvent)=>{if(!start)return;const x=start.left+e.clientX-start.x,y=start.top+e.clientY-start.y;n.dataset.lx=String(x);n.dataset.ly=String(y);n.style.transform=`translate(${x}px,${y}px) ${mode==="gravity"?"rotate(1deg)":""}`};const up=()=>start=null;n.addEventListener("pointerdown",down);n.addEventListener("pointermove",move);n.addEventListener("pointerup",up);cleanups.push(()=>{n.removeEventListener("pointerdown",down);n.removeEventListener("pointermove",move);n.removeEventListener("pointerup",up);n.classList.remove(styles.window,styles.falling);n.removeAttribute("data-lx");n.removeAttribute("data-ly");if(old===null)n.removeAttribute("style");else n.setAttribute("style",old);}); }); }
function Minesweeper({close}:{close:()=>void}){const [board,setBoard]=useState<Board>(()=>makeBoard()),[cursor,setCursor]=useState([0,0]);const state=boardState(board);const act=(x:number,y:number,flag=false)=>setBoard(b=>flag?toggleFlag(b,x,y):reveal(b,x,y));return <div className={styles.win95} role="dialog" aria-modal="true" aria-label="Minesweeper"><header><b>Minesweeper</b><button onClick={close} aria-label="Close">×</button></header><div className={styles.mineStatus}>{state==="playing"?"🙂":state==="won"?"😎":"😵"} {state}</div><div className={styles.board} role="grid" onKeyDown={e=>{let[x,y]=cursor;if(e.key==="ArrowRight")x++;if(e.key==="ArrowLeft")x--;if(e.key==="ArrowDown")y++;if(e.key==="ArrowUp")y--;x=Math.max(0,Math.min(8,x));y=Math.max(0,Math.min(8,y));setCursor([x,y]);if(e.key===" "||e.key==="Enter"){e.preventDefault();act(x,y,e.shiftKey)}}}>{board.map((row,y)=>row.map((c,x)=><button key={`${x}-${y}`} role="gridcell" tabIndex={cursor[0]===x&&cursor[1]===y?0:-1} aria-label={`${c.open?c.mine?"mine":c.adjacent||"empty":c.flagged?"flagged":"covered"}, row ${y+1}, column ${x+1}`} onFocus={()=>setCursor([x,y])} onClick={()=>act(x,y)} onContextMenu={e=>{e.preventDefault();act(x,y,true)}} className={c.open?styles.open:""}>{c.open?(c.mine?"💣":c.adjacent||""):c.flagged?"🚩":""}</button>))}</div><footer>Enter reveals. Shift+Enter or long press menu flags.</footer></div>}
function Paint({register}:{register:(fn:()=>void)=>void}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const c=ref.current!,ctx=c.getContext("2d")!;let points:{x:number;y:number;t:number}[]=[];const resize=()=>{c.width=innerWidth;c.height=innerHeight};const draw=(e:PointerEvent)=>{points.push({x:e.clientX,y:e.clientY,t:Date.now()});points=points.filter(p=>Date.now()-p.t<1800);ctx.clearRect(0,0,c.width,c.height);ctx.lineWidth=4;ctx.strokeStyle="#a8ff78";ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke()};resize();addEventListener("resize",resize);addEventListener("pointermove",draw);register(()=>{removeEventListener("resize",resize);removeEventListener("pointermove",draw);ctx.clearRect(0,0,c.width,c.height)});return()=>{}},[register]);return <canvas ref={ref} className={styles.canvas} aria-hidden="true"/>}
function Ambient({register}:{register:(fn:()=>void)=>void}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const c=ref.current!,x=c.getContext("2d")!;let id=0,t=0;const seed=Number(sessionStorage.getItem("lab-seed")||Math.floor(Math.random()*99999));sessionStorage.setItem("lab-seed",String(seed));const resize=()=>{c.width=innerWidth;c.height=innerHeight};const frame=()=>{t+=.003;x.fillStyle="rgba(8,8,12,.08)";x.fillRect(0,0,c.width,c.height);for(let i=0;i<18;i++){x.fillStyle=`hsla(${(seed+i*31+t*100)%360},55%,60%,.18)`;x.beginPath();x.arc((Math.sin(t+i+seed)*.45+.5)*c.width,(Math.cos(t*.7+i)*.45+.5)*c.height,20+i*2,0,7);x.fill()}id=requestAnimationFrame(frame)};resize();frame();addEventListener("resize",resize);register(()=>{cancelAnimationFrame(id);removeEventListener("resize",resize);x.clearRect(0,0,c.width,c.height)});},[register]);return <canvas ref={ref} className={styles.ambient} aria-label="Silent deterministic ambient screensaver"/>}
function Typing(){const [round,setRound]=useState(0),[typed,setTyped]=useState(""),[start,setStart]=useState(0);const target=words[round%words.length],score=scoreTyping(target,typed,start?Date.now()-start:0);return <div className={styles.panel} role="dialog" aria-label="Typing game"><small>LOCAL-ONLY TYPING LAB</small><h2>{target}</h2><input autoFocus value={typed} onChange={e=>{if(!start)setStart(Date.now());setTyped(e.target.value)}} aria-label="Type the phrase"/><p>{score.accuracy}% accuracy · {score.wpm} WPM</p>{typed===target&&<button onClick={()=>{setRound(r=>r+1);setTyped("");setStart(0)}}>Next phrase</button>}</div>}
function Diagnostics(){return <div className={styles.panel} role="dialog" aria-label="Whimsical diagnostics"><small>SIMULATED · NOT REAL TELEMETRY</small><h2>System whimsy</h2><dl><dt>Pixel confidence</dt><dd>98.4%</dd><dt>Layout vibes</dt><dd>Nominal</dd><dt>Semicolon pressure</dt><dd>12 biscuits</dd><dt>Visitor tracking</dt><dd>Absolutely not in this panel</dd></dl></div>}
